account_id                = 773731497343
kms_key_id                = ""
kms_description           = ""
vpc_name                  = "dev"
lb_name                   = ""
lb_arn                    = ""
route53_zone_name         = ""
route53_genomic_zone_name = ""
route53_ac_zone_name      = ""
route53_public_zone_name  = ""
ecs_cluster_name          = ""
internal_listener_arn     = ""
external_ssl_listener_arn = ""


default_tags = {
  "Environment"              = ""
  "Organization"             = " "
  "Provisioner"              = "Terraform"
  "Service"                  = " "
  "Squad"                    = "   "
  "map-migrated"             = "k"
  "aws-migration-project-id" = ""
  "Component"                =   ""
}

map_tags = {
  "map-migrated"             = ""
  "aws-migration-project-id" = ""
}




# autogenerated - DO NOT EDIT!
hosts = {  }
